# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1980243-Weather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1980243-Weather
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'

end
